package test1;

import org.testng.annotations.Test;

public class TimeoutAndException {
 /* 
  // invocationTimeout = 2 , wait for 2 seconds
  //expectedExceptions = NumberFormatException.class is the exception that may occur
	// for both exception and timeout
  @Test(invocationTimeOut=2, expectedExceptions = NumberFormatException.class)
  public void infiniteloop() {
	  int i=1;
	  while (i==1) {
		  System.out.println(i);
	  }
  }
  */